/*
 * SEVEN_SEGMENT.h
 */ 


#ifndef SEVEN_SEGMENT_H_
#define SEVEN_SEGMENT_H_

void SEVEN_SEGMENT_INITIALIZATION();

void SEVEN_SEGMENT_WRITE_NUMBER(unsigned char number);

void SEVEN_SEGMENT_ENABLE1();

void SEVEN_SEGMENT_DISABLE1();

void SEVEN_SEGMENT_ENABLE2();

void SEVEN_SEGMENT_DISABLE2();



#endif /* SEVEN_SEGMENT_H_ */